# Generated by Django 3.1 on 2020-12-06 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('judet', models.CharField(max_length=100)),
                ('localitate', models.CharField(max_length=100)),
                ('strada', models.CharField(max_length=100)),
                ('numar', models.CharField(max_length=100)),
                ('bloc', models.CharField(max_length=100)),
                ('scara', models.CharField(max_length=100)),
                ('ap', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('telefon', models.CharField(max_length=100)),
                ('cantitate', models.IntegerField()),
                ('selling_what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
    ]
